#!/bin/sh

# modify default.conf and docker-compose.yml and run the docker containers

# Usage:
# ./run

# nginx
cd nginx
cp default.conf.template default.conf

if [ "$os" = "Linux" ]; then
  replace_host=s/{HOST}/$host/g
  sed -i "$replace_host" default.conf
else
  replace_host=s/{HOST}/$host/g
  perl -p -i -e "$replace_host" default.conf
fi

cd ..
# build
docker-compose build --no-cache

# run
docker-compose up
